### ISSUE TITLE
Publication and Subscriber models not apperaing in the admin area.

### ISSUE THREAD

**Issue by HHtech-hub** [marcelovicentegc/django-react-typescript#52]
I think you need to import the classes in the admin folders `__init__.py` otherwise django doesn't pick them up.

Adding
```
from .publications import PublicationAdmin
from .subscribers import SubscriberAdmin
```
to
```django-react-typescript\backend\admin\__init__.py```

as per:
https://stackoverflow.com/questions/61818175/defning-django-admin-models-inside-subdirectories-instead-of-admin-py

**Comment by marcelovicentegc** [comment]
Hey @HHtech-hub, truestory! My bad. I removed them because ruff was accusing these classes were not being used. As it's been a while since I've played with Django, I'm still re-familiarizing with it. 

Would you mind opening a PR adding these imports + ignoring this file on `ruff.toml`?
